name: CI
on: [push, pull_request]
jobs:
  buildCLI:
    name: "Build CLI"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[CI_SKIP]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --bin chalk

      - name: Test

        run: cargo test  --bin chalk

  buildDaemon:
    name: "Build Daemon"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI_SKIP]')"

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --bin chalk_daemon

      - name: Test
        run: cargo test --bin chalk_daemon
